addSbtPlugin("com.dwijnand"      % "sbt-dynver"            % "3.0.0")
addSbtPlugin("com.dwijnand"      % "sbt-travisci"          % "1.1.1")
addSbtPlugin("com.geirsson"      % "sbt-scalafmt"          % "1.4.0")
addSbtPlugin("de.heikoseeberger" % "sbt-header"            % "5.0.0")
addSbtPlugin("com.typesafe.sbt"  % "sbt-native-packager"   % "1.3.4")
addSbtPlugin("com.47deg"         % "sbt-microsites"        % "0.7.18")
